### ISSUE TITLE
Able to Send Message in Order Chat

### ISSUE THREAD

**Issue by tony-tripulca** [tony-tripulca/binance-p2p#1]
We are looking to add a functionality where we can send message in the orders chat through API.

**Comment by tony-tripulca** [comment]
![image](https://user-images.githubusercontent.com/33964689/198153576-946c2192-ef31-442b-9cc6-36815c391d38.png)

**Comment by tony-tripulca** [comment]
As per Binance API support, there's no endpoint for sending message yet.

**Comment by tony-tripulca** [comment]
This is unfortunate @angel-rs

**Comment by angel-rs** [comment]
> This is unfortunate @angel-rs 

Indeed. 

Thank you for keeping me in the loop on this @tony-tripulca
