### ISSUE TITLE
Able to Update Price of P2P Ads

### ISSUE THREAD

**Issue by tony-tripulca** [tony-tripulca/binance-p2p#4]
We are looking to update the price of the published ads in P2P via API.

**Comment by nicoasdd** [comment]
@tony-tripulca Interested in contribute, sent an email @angel-rs to if you guys want to check it out.

**Comment by lumpov** [comment]
@angel-rs do you have solution for that?

**Comment by angel-rs** [comment]
Not via API @lumpov 

Ended up doing an automation w/ playwright to update the price of an existing ad.

**Comment by lumpov** [comment]
@angel-rs could you share your solution?

**Comment by angel-rs** [comment]
Sure @lumpov, where can I reach out to you?
